name: Pull Request
description: Pull request template
title: "[🌞Feat]: "
labels: ["feat"]
projects: ["baedal-legend"]
body:
  - type: markdown
    attributes:
      value: |
        변경사항이 무엇인지, 어떤 작업내용을 포함하는지 작성해 주세요.

  - type: input
    id: summation
    attributes:
      label: 변경사항은 무엇인가요?
      description: 변경사항에 대해 간략하게 설명해주세요.
      placeholder: 변경사항에 대해 간략하게 설명해주세요.
      value: "변경사항에 대해 간략하게 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 변경사항에는 무엇이 있나요?
      description: 변경 사항이 어떤 내용을 포함하는지 설명해주세요.
      placeholder: 변경 사항이 어떤 내용을 포함하는지 설명해주세요.
      value: "변경 사항이 어떤 내용을 포함하는지 설명해주세요."
      render: text
    validations:
      required: true

  - type: input
    id: related-issue
    attributes:
      label: 해당 변경사항에 관련된 이슈는 무엇인가요?
      description: 해당 변경사항에 관련된 이슈는 무엇인가요?
      placeholder: #1, #2, #3
      value: "#"
    validations:
      required: true

  - type: checkboxes
    id: todo-list
    attributes:
      label: 변경을 위해 작업한 내용을 입력해주세요.
      description: 변경을 위해 작업한 내용을 입력해주세요.
      options:
        - label: TODO 1
        - label: TODO 2
        - label: TODO 3

  - type: textarea
    id: test-methods
    attributes:
      label: 변경 사항을 확인하기 위해 테스트한 방법을 설명해주세요.
      description: 변경 사항을 확인하기 위해 테스트한 방법을 설명해주세요.

  - type: checkboxes
    id: tests-implemented
    attributes:
      label: 테스트 작성 여부
      description: 해당 기능에 대한 테스트가 작성 되었나요?
      options:
        - label: 해당 기능에 대한 테스트가 작성 되었나요?
          required: true
