server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
